CREATE TABLE `IT202_F25_User_Jobs` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `job_id` VARCHAR(128) NOT NULL,
    `user_id` INT NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `is_active` TINYINT(1) DEFAULT 1,
    FOREIGN KEY (`job_id`) REFERENCES `IT202_F25_Jsearch` (`job_id`) ON DELETE CASCADE,
    FOREIGN KEY (`user_id`) REFERENCES `Users` (`id`) ON DELETE CASCADE,
    UNIQUE KEY (`user_id`, `job_id`)
);
